[build]
target = "armv7a-none-eabi"

[unstable]
build-std = ["core"]
build-std-features = ["compiler-builtins-mem"]

[target.armv7a-none-eabi]
rustflags = [
    "-C", "link-arg=-Tlinker.ld",
    "-C", "link-arg=--build-id=none",
    "-C", "target-cpu=cortex-a7",
]
